apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaaladin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaaladin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: vaaladin
    spec:
      automountServiceAccountToken: false
      containers:
        - name: vaaladin
          image: vaaladin
          imagePullPolicy: "Never"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "800m"
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=80 -XX:+UseZGC -XX:+ZGenerational"
---
## setup pod monitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vaaladin-pod-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: vaaladin
  podMetricsEndpoints:
    - port: web
      path: /actuator/prometheus
      interval: 5s
      scheme: http
      tlsConfig:
        insecureSkipVerify: true
