spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:vaaladin;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;MODE=MYSQL;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=true
    username: vaaladin
    password: password123
  h2:
    console:
      enabled: true
vaadin:
  launch-browser: true
logging:
  config: classpath:logback-simple.xml


