spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:mem:optosoft;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;MODE=MYSQL;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=true
    username: sa
  h2:
    console:
      enabled: true
  security:
    user:
      name: user
      password: password
vaadin:
  launch-browser: true
logging:
  level:
    root: info
    com.samsoft: debug


