server:
  port: ${PORT:8080}
spring:
  application:
    name: vaaladin
  main:
    banner-mode: off
  mustache:
    check-template-location: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
vaadin:
  launch-browser: false
logging:
  level:
    root: warn
    com.samsoft: info
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true