server:
  port: ${PORT:8080}
spring:
  application:
    name: vaaladin
  main:
    banner-mode: off
  mustache:
    check-template-location: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
  threads:
    virtual:
      enabled: true
vaadin:
  launch-browser: false
logging:
  config: classpath:logback.xml
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

