logging:
  level:
    root: error
    org.springframework: warn
    com.samsoft: debug
server:
  port: ${PORT:8080}

spring:
  application:
    name: trueyes
  main:
    banner-mode: "off"
  jpa:
    # enable JPA to auto-create the database schema and tables for JPA entities
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  mustache:
    check-template-location: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/samsoft
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    # add property for pool size and connection timeout
    hikari:
      pool-name: samsoft
      maximum-pool-size: 5
      connection-timeout: 500
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            user-info-uri: "https://www.googleapis.com/oauth2/v3/userinfo"
  output:
    ansi:
      enabled: "always"
vaadin:
  allowed-packages: com.vaadin,org.vaadin,com.samsoft.trueyes
  devmode-caching: false
  launch-browser: false
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
